### ISSUE TITLE
Xen Orchestra provider?

### ISSUE THREAD

**Issue by olivierlambert** [amfranz/terraform-provider-xenserver#7]
Using Xen Orchestra API as an endpoint for Terraform would allow you to control multiple pools at once, using a dedicated API that "hide" the inherent XAPI complexity.

If you need assistance on doing that, let me know (we got also a CLI).

**Comment by ringods** [comment]
@olivierlambert given you have a totally different API, it's not feasible to mix your API in this provider. I would suggest to start a separate `terraform-provider-xenorchestra` codebase optimized to use the Xen Orchestra API.

Nevertheless, good idea! ;-)

**Comment by olivierlambert** [comment]
Well, in fact that was my point by poorly described :p It was to create a terraform driver for XO to be able to do things faster and on multiple pools at once (because XO is a central point). /my2 cents, I don't need have the resources/knowledge to do the terraform thing, but let me know if you want to do so :)

**Comment by ringods** [comment]
@olivierlambert I'm just a sole contributor to this project. To be clear, I'm not going to start the initiative for a XO provider.

**Comment by olivierlambert** [comment]
Understood :) Let me know if it changes :+1:

**Comment by ddelnano** [comment]
@olivierlambert I'm interested in writing a provider for the XO api. Unfortunately I can't seem to find any documentation on this.

**Comment by ringods** [comment]
@ddelnano feel free to have it hosted under the terra-farm wings.

**Comment by olivierlambert** [comment]
@ddelnano sure I can help :) Our `xo-server` lead dev is on Freenode in #xen-orchestra channel (it's `julien-f`) if you want to discuss

Also, XO API is a JSON-RPC API, and you can check all the possible calls using `xo-cli` ([doc here](https://xen-orchestra.com/docs/xo-cli.html)).

`xo-lib` could be also useful to reuse for you (see [here](https://github.com/vatesfr/xen-orchestra/tree/master/packages/xo-lib)).

We'll provide all the assistance you need on XO side :+1:

**Comment by ringods** [comment]
@ddelnano I was so free to set you up with a repository for this provider.

https://github.com/terra-farm/terraform-provider-xenorchestra

You should have received a Github invite for this repository. The setup was done via Terraform itself in [this commit](https://github.com/terra-farm/terraform-github-org/commit/72125d34c98ef2d376f4562c0ebfc07ad6572d0c). If you need a change to the repository setup, please file in issue or create a PR.

I can help you out with how to document the provider to have it automatically published on https://terra-farm.github.io. Don't look at the look&feel of that site at the moment. But the tooling is the same as backing the [Couchbase docs](https://docs.couchbase.com). Still needs some attention from my end. 😉

**Comment by ddelnano** [comment]
:+1:. I'm just getting started. Sometime next week I might have something to show.

**Comment by ringods** [comment]
@ddelnano no stress. It's your provider after all. 😉  If you need my attention for the docs, create an issue in your own provider repository and @-mention me. I use https://octobox.io to follow up on all my Github notifications.

**Comment by deligatedgeek** [comment]
Hi @olivierlambert @ringods @ddelnano,

I have seen the Xen Orchestrator provider in Terrafarm, it is good but it doesn't appear to work in complex environments.

I have modified to implementation for more complex requirements, but cannot create a VM due to something to do the VM network interface.  If anyone is still working on this I'd appreciate some help in the future.

**Comment by ringods** [comment]
@deligatedgeek please create an issue in the xenorchestra provider project:

https://github.com/terra-farm/terraform-provider-xenorchestra
